Announcement: NovaCustom NV41 Series available with Heads
QubesOS/qubes-posts pull request #127
Opened 2024-02-23 21:38 UTC by andrewdavidwong

Does this look okay, @wessel-novacustom?

2024-02-24 09:47 UTC, wessel-novacustom requested changes
It is almost perfect, but I have two suggestions for improvement.

Instead of:

> you can now choose either Dasharo coreboot or Heads for the firmware

I would prefer: _you can now choose either Dasharo coreboot+EDK-II (default) or Dasharo coreboot+Heads for the firmware_.

Also, I would change line 12 to:

_Current NV41 Series owners who wish to change from Dasharo coreboot+EDK-II to the Heads firmware version can [buy the Dasharo Entry Subscription](https://novacustom.com/product/dasharo-entry-subscription/) for an easy transition to Heads._

@macpijan is finalising the documentation on docs.dasharo.com, please wait with the publication of the announcement till you have received our confirmation.

2024-02-24 23:52 UTC, andrewdavidwong commented
> It is almost perfect, but I have two suggestions for improvement.
> 
> Instead of:
> 
> > you can now choose either Dasharo coreboot or Heads for the firmware
> 
> I would prefer: _you can now choose either Dasharo coreboot+EDK-II (default) or Dasharo coreboot+Heads for the firmware_.
> 
> Also, I would change line 12 to:
> 
> _Current NV41 Series owners who wish to change from Dasharo coreboot+EDK-II to the Heads firmware version can [buy the Dasharo Entry Subscription](https://novacustom.com/product/dasharo-entry-subscription/) for an easy transition to Heads._
> 

Both changes implemented. Thank you!

> @macpijan is finalising the documentation on docs.dasharo.com, please wait with the publication of the announcement till you have received our confirmation.

Understood. We'll put this PR on hold until then.

2024-02-29 00:54 UTC, marmarek approved these changes
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Approved as of 0631b628d74d91153567858bab194596916fc7ee
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCAAdFiEEnYWYU8Ll1fIX9iss8yiUvpaEk4oFAmXf1cYACgkQ8yiUvpaE
k4rhEg//Ydzr/MTUiNyrSiXs5nC6qVcmpIzzZdm5ruS85FDUx3mmoUBTFi1a7ja1
R3QBnxVrNbB/tL3NQWaszm5a0saMZOdbBwmXBO33/LJ+iPGOGkmIUSDZ/jpcGGcq
F+dBTGX/XKMWExW0bWJu58Tzp6I8BTfczXHQQR4dKAlesuNXC06JVmvzVNdDL5Yz
9ehzJhZy6a+gYn7oXvPUxgm/ADdFVaPBEy+Vn29MjkfnWjPgcOzlwUom/dm0ZN87
/EO4uZxHou/P8WurzHVEBwBF6yjDE8GLjcrli+xg2zR/2gRQyUIFLSmQQXHeuC3c
enf24iL0ohQaCju77IZwvLcZZyc7cY1i9sLwVbdhfrdOFhkYEdGzbW24FuZ2zQ3v
Sg9yIDVsHX0Bydo6QRuAR3HIJnZj9y2IDgOTGPrIYw8kAfWcCoNiZEw0qWADacCP
4QRgcaOQZs+ZGDLpWxeSdwrw4ULoubyXsf0eI70X35c2mFWbj1v7sLB4bRMlvwee
Lf7KxCgjV0OgTVfY1RQaoHwLvidpkcoW8qJtrec+xlW8IOAemRWlqK+rRui1psCp
RO+q5peO8NW39E41buAy5LfHpwREmscE7DD8N5Qy0QpvagP1qStbB3l9Tj2Jy0j3
SLmcuz/X0kxBsfIOxcADYmzgSqRYZXyZ8ECFIDsS7G3dRiVUi0g=
=W3gl
-----END PGP SIGNATURE-----
```

2024-03-03 13:17 UTC, wessel-novacustom commented
> ```
> -----BEGIN PGP SIGNED MESSAGE-----
> Hash: SHA256
> 
> Approved as of 0631b628d74d91153567858bab194596916fc7ee
> -----BEGIN PGP SIGNATURE-----
> 
> iQIzBAEBCAAdFiEEnYWYU8Ll1fIX9iss8yiUvpaEk4oFAmXf1cYACgkQ8yiUvpaE
> k4rhEg//Ydzr/MTUiNyrSiXs5nC6qVcmpIzzZdm5ruS85FDUx3mmoUBTFi1a7ja1
> R3QBnxVrNbB/tL3NQWaszm5a0saMZOdbBwmXBO33/LJ+iPGOGkmIUSDZ/jpcGGcq
> F+dBTGX/XKMWExW0bWJu58Tzp6I8BTfczXHQQR4dKAlesuNXC06JVmvzVNdDL5Yz
> 9ehzJhZy6a+gYn7oXvPUxgm/ADdFVaPBEy+Vn29MjkfnWjPgcOzlwUom/dm0ZN87
> /EO4uZxHou/P8WurzHVEBwBF6yjDE8GLjcrli+xg2zR/2gRQyUIFLSmQQXHeuC3c
> enf24iL0ohQaCju77IZwvLcZZyc7cY1i9sLwVbdhfrdOFhkYEdGzbW24FuZ2zQ3v
> Sg9yIDVsHX0Bydo6QRuAR3HIJnZj9y2IDgOTGPrIYw8kAfWcCoNiZEw0qWADacCP
> 4QRgcaOQZs+ZGDLpWxeSdwrw4ULoubyXsf0eI70X35c2mFWbj1v7sLB4bRMlvwee
> Lf7KxCgjV0OgTVfY1RQaoHwLvidpkcoW8qJtrec+xlW8IOAemRWlqK+rRui1psCp
> RO+q5peO8NW39E41buAy5LfHpwREmscE7DD8N5Qy0QpvagP1qStbB3l9Tj2Jy0j3
> SLmcuz/X0kxBsfIOxcADYmzgSqRYZXyZ8ECFIDsS7G3dRiVUi0g=
> =W3gl
> -----END PGP SIGNATURE-----
> ```

Thank you for replying, however, I cannot see this message.

I have seen the changes though and I can confirm everything is fine now, so you can publish it.

2024-03-04 03:18 UTC, andrewdavidwong commented
> > ```
> > -----BEGIN PGP SIGNED MESSAGE-----
> > Hash: SHA256
> > 
> > Approved as of 0631b628d74d91153567858bab194596916fc7ee
> > -----BEGIN PGP SIGNATURE-----
> > 
> > iQIzBAEBCAAdFiEEnYWYU8Ll1fIX9iss8yiUvpaEk4oFAmXf1cYACgkQ8yiUvpaE
> > k4rhEg//Ydzr/MTUiNyrSiXs5nC6qVcmpIzzZdm5ruS85FDUx3mmoUBTFi1a7ja1
> > R3QBnxVrNbB/tL3NQWaszm5a0saMZOdbBwmXBO33/LJ+iPGOGkmIUSDZ/jpcGGcq
> > F+dBTGX/XKMWExW0bWJu58Tzp6I8BTfczXHQQR4dKAlesuNXC06JVmvzVNdDL5Yz
> > 9ehzJhZy6a+gYn7oXvPUxgm/ADdFVaPBEy+Vn29MjkfnWjPgcOzlwUom/dm0ZN87
> > /EO4uZxHou/P8WurzHVEBwBF6yjDE8GLjcrli+xg2zR/2gRQyUIFLSmQQXHeuC3c
> > enf24iL0ohQaCju77IZwvLcZZyc7cY1i9sLwVbdhfrdOFhkYEdGzbW24FuZ2zQ3v
> > Sg9yIDVsHX0Bydo6QRuAR3HIJnZj9y2IDgOTGPrIYw8kAfWcCoNiZEw0qWADacCP
> > 4QRgcaOQZs+ZGDLpWxeSdwrw4ULoubyXsf0eI70X35c2mFWbj1v7sLB4bRMlvwee
> > Lf7KxCgjV0OgTVfY1RQaoHwLvidpkcoW8qJtrec+xlW8IOAemRWlqK+rRui1psCp
> > RO+q5peO8NW39E41buAy5LfHpwREmscE7DD8N5Qy0QpvagP1qStbB3l9Tj2Jy0j3
> > SLmcuz/X0kxBsfIOxcADYmzgSqRYZXyZ8ECFIDsS7G3dRiVUi0g=
> > =W3gl
> > -----END PGP SIGNATURE-----
> > ```
> 
> Thank you for replying, however, I cannot see this message.
> 

That's not an encrypted message. It's just a clearsigned message indicating that this PR has passed @marmarek's review, per our [documentation security procedures](https://www.qubes-os.org/doc/how-to-edit-the-documentation/#security). The clearsigned content of the message is just the fourth line, `Approved as of 0631b628d74d91153567858bab194596916fc7ee`.

> I have seen the changes though and I can confirm everything is fine now, so you can publish it. Heads has been released now for our laptop series:
> 
> * https://novacustom.com/dasharo-coreboot-plus-heads-firmware-version/
> * https://docs.dasharo.com/variants/novacustom_nv4x_adl/heads/

Okay, thanks! I'll proceed to publish this now.

2024-03-04 03:20 UTC, merged